{
 "title": "Engineering Overview",
 "tags": [
  "Engineering Leads Dashboard",
  "Highlights"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "month",
    "label": "Selected Month",
    "query": "select\n  distinct(concat(date_format(month_timestamp, '%Y-%m') , ':', date_format(month_timestamp, '%Y-%m-%d'))) as month\nfrom\n  calendar_months\nwhere \n  month_timestamp <= curdate()\norder by month desc\nlimit 12"
   },
   {
    "name": "priority",
    "label": "Prioriti(es) of Critical Issues",
    "query": "select distinct priority from issues"
   },
   {
    "name": "type",
    "label": "Issue Type",
    "query": "select distinct type from issues"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard is to overview the Git and project management metrics.\n- Data Source Required: Jira + GitHub, or Jira + GitLab."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Critical Defects Identified [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct i.id)\nfrom\n  issues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\n\tjoin project_mapping pm on b.id = pm.row_id\nwhere\n  pm.project_name in (${project}) and\n  i.priority in (${priority}) and\n  i.type = 'BUG' and\n  date(i.created_date) between STR_TO_DATE('$month','%Y-%m-%d') and STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH;"
    }
   ]
  },
  {
   "title": "Critical Defects Identified over Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 3 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  select\n    DATE_ADD(date(i.created_date), INTERVAL -DAY(date(i.created_date))+1 DAY) as time,\n    count(distinct i.id) as defect_count\n  from\n    issues i\n    join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  where\n    pm.project_name in (${project}) and\n    i.priority in (${priority})\n    and i.type = 'BUG'\n    and $__timeFilter(i.created_date)\n    and i.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by time\n)\n\nselect\n  date_format(time,'%M %Y') as month,\n  defect_count\nfrom _issues\norder by time asc\n"
    }
   ]
  },
  {
   "title": "Mean Issue Lead Time in Days [Issues Resolved in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  avg(lead_time_minutes/1440) as value\r\nfrom issues i\r\n\tjoin board_issues bi on i.id = bi.issue_id\r\n\tjoin boards b on bi.board_id = b.id\r\n\tjoin project_mapping pm on b.id = pm.row_id\r\nwhere \r\n  pm.project_name in (${project}) and\r\n  i.type in (${type})\r\n  and i.status = 'DONE'\r\n  and i.resolution_date between STR_TO_DATE('$month','%Y-%m-%d') and STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH;"
    }
   ]
  },
  {
   "title": "Mean Requirement Lead Time in Days [Of Issues Resolved per Month]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    DATE_ADD(date(i.resolution_date), INTERVAL -DAY(date(i.resolution_date))+1 DAY) as time,\n    AVG(i.lead_time_minutes/1440) as issue_lead_time\n  FROM issues i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  WHERE\n    pm.project_name in (${project})\n    and i.status = \"DONE\"\n    and $__timeFilter(i.resolution_date)\n    and i.resolution_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  date_format(time,'%M %Y') as month,\n  issue_lead_time as \"Mean Requirement Lead Time in Days\"\nFROM _issues\nORDER BY time"
    }
   ]
  },
  {
   "title": "Number of Developers [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct author_name)\nfrom\n  commits c\n  join repo_commits rc on c.sha = rc.commit_sha\n  join project_mapping pm on rc.repo_id = pm.row_id and pm.table = 'repos' \nwhere\n  date(authored_date) between STR_TO_DATE('$month','%Y-%m-%d') and STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH\n  and pm.project_name in (${project})"
    }
   ]
  },
  {
   "title": "Number of Developers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 19 },
   "targets": [
    {
     "rawSql": "with _developers as(\n  select\n    DATE_ADD(date(c.authored_date), INTERVAL -DAY(date(c.authored_date))+1 DAY) as time,\n    count(distinct author_name) as developer_count\n  from\n    commits c\n    join repo_commits rc on c.sha = rc.commit_sha\n    join project_mapping pm on rc.repo_id = pm.row_id and pm.table = 'repos' \n  where\n    $__timeFilter(c.authored_date)\n    and c.authored_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and pm.project_name in (${project})\n  group by time\n)\n\nselect\n  date_format(time,'%M %Y') as month,\n  developer_count\nfrom _developers\norder by time asc"
    }
   ]
  },
  {
   "title": "On-time Delivery [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _num_issues_with_sprint_updated as (\n  select\n    NULLIF(COUNT(DISTINCT i.id), 0) AS num_issues_with_sprint_updated\n  from\n    issues i\n    join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n    join issue_changelogs c on i.id = c.issue_id\n  where\n    pm.project_name in (${project}) and\n    c.field_name = 'Sprint' and\n    c.original_from_value != '' and\n    c.original_to_value != '' and\n    date(i.created_date) between\n      STR_TO_DATE('$month','%Y-%m-%d') and\n      STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH\n),\n\n_total_num_issues as (\n  select\n    NULLIF(COUNT(distinct i.id), 0) as total_num_issues\n  from\n    issues i\n    join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  where\n    pm.project_name in (${project}) and\n    date(i.created_date) between\n      STR_TO_DATE('$month','%Y-%m-%d') and\n      STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH\n)\n\nselect\n  now() as time,\n  100 - 100 * (select 1.0 * num_issues_with_sprint_updated from _num_issues_with_sprint_updated) / (select total_num_issues from _total_num_issues) as ratio;"
    }
   ]
  },
  {
   "title": "On-time Delivery over Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "with _num_issues_with_sprint_updated as (\n  select\n    DATE_ADD(date(i.created_date), INTERVAL -DAY(date(i.created_date))+1 DAY) as time,\n    NULLIF(COUNT(DISTINCT i.id), 0) AS num_issues_with_sprint_updated\n  from\n    issues i\n    join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n    join issue_changelogs c on i.id = c.issue_id\n  where\n    pm.project_name in (${project}) and\n    c.field_name = 'Sprint'\n    and c.original_from_value != '' \n    and c.original_to_value != ''\n    and $__timeFilter(i.created_date)\n    and i.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by time\n),\n\n_total_num_issues as (\n  select\n    DATE_ADD(date(i.created_date), INTERVAL -DAY(date(i.created_date))+1 DAY) as time,\n    NULLIF(COUNT(distinct i.id), 0) as total_num_issues\n  from\n    issues i\n    join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  where\n    pm.project_name in (${project}) and\n    $__timeFilter(i.created_date)\n    and i.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by time\n)\n\nselect\n  x.time,\n  100 - 100 * (1.0 * x.num_issues_with_sprint_updated / y.total_num_issues) as delivery_rate\nfrom \n  _num_issues_with_sprint_updated x \n  join _total_num_issues y on x.time = y.time"
    }
   ]
  },
  {
   "title": "PRs merged [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct pr.id)\nfrom\n  pull_requests pr\n  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nwhere\n  pr.merged_date is not null \n  and date(pr.merged_date) between\n    STR_TO_DATE('$month','%Y-%m-%d')\n  and STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH\n  and pm.project_name in (${project});"
    }
   ]
  },
  {
   "title": "PRs Merged over Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 35 },
   "targets": [
    {
     "rawSql": "with _merged_prs as(\n  select\n    DATE_ADD(date(pr.merged_date), INTERVAL -DAY(date(pr.merged_date))+1 DAY) as time,\n    count(distinct pr.id) as pr_merged_count\n  from\n    pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  where\n    pm.project_name in (${project})\n    and pr.merged_date is not null\n    and $__timeFilter(pr.merged_date)\n    and pr.merged_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by time\n)\n\nselect\n  date_format(time,'%M %Y') as month,\n  pr_merged_count\nfrom _merged_prs\norder by time asc"
    }
   ]
  },
  {
   "title": "Unlinked PRs % [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  100*count(distinct case when pr.id in (select pull_request_id from pull_request_issues) then pr.id else null end)/count(distinct pr.id) as unlinked_pr_rate\nfrom pull_requests pr\njoin project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nwhere \n  pm.project_name in (${project})\n  and date(pr.created_date) between STR_TO_DATE('$month','%Y-%m-%d') and STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH"
    }
   ]
  },
  {
   "title": "Unlinked PRs Ratio over Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\n  DATE_ADD(date(created_date), INTERVAL -DAY(date(created_date))+1 DAY) as time,\n  100*count(distinct case when pr.id in (select pull_request_id from pull_request_issues) then pr.id else null end)/count(distinct pr.id) as unlinked_pr_rate\nfrom pull_requests pr\njoin project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nwhere pm.project_name in (${project})\nand $__timeFilter(created_date)\nand created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\ngroup by time\n\n"
    }
   ]
  },
  {
   "title": "Coding Days % [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _commits_groupby_name_and_date as (\n  select\n    author_name,\n    date(authored_date) as _day,\n    count(distinct c.sha)\n  from\n    commits c\n    join repo_commits rc on c.sha = rc.commit_sha\n    join project_mapping pm on rc.repo_id = pm.row_id\n  where\n    pm.project_name in (${project}) and\n    WEEKDAY(authored_date) between 0 and 4 and\n    date(authored_date) between\n      STR_TO_DATE('$month','%Y-%m-%d') and\n      STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH\n  group by\n  author_name, date(authored_date)\n)\n\nselect 100 * count(*) / (count(distinct author_name) * count(distinct _day))\nfrom _commits_groupby_name_and_date;"
    }
   ]
  },
  {
   "title": "Percentage of Coding Days Each Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "with _commits_groupby_name_and_date as (\n  select\n    author_name,\n    date(authored_date) as _day,\n    count(distinct c.sha)\n  from\n    commits c\n    join repo_commits rc on c.sha = rc.commit_sha\n    join project_mapping pm on rc.repo_id = pm.row_id\n  where\n    pm.project_name in (${project}) and\n    (WEEKDAY(authored_date) between 0 and 4)\n    and $__timeFilter(authored_date)\n    and authored_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1,2\n)\n\nselect\n  DATE_ADD(_day, INTERVAL -DAY(_day)+1 DAY) as time,\n  100*count(*)/(count(distinct author_name) * count(distinct _day)) as working_days_percentatages_per_month\nfrom _commits_groupby_name_and_date\ngroup by time"
    }
   ]
  },
  {
   "title": "Mean Time to Merge [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  AVG(TIMESTAMPDIFF(MINUTE, pr.created_date, pr.merged_date) / 1440)\nfrom\n  pull_requests pr\n  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nwhere\n  pm.project_name in (${project}) and\n  pr.merged_date is not null\n  and date(pr.created_date) between\n    STR_TO_DATE('$month','%Y-%m-%d') \n    and STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH"
    }
   ]
  },
  {
   "title": "Mean Time to Merge over Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "select\n  DATE_ADD(date(pr.created_date), INTERVAL -DAY(date(pr.created_date))+1 DAY) as time,\n  AVG(TIMESTAMPDIFF(MINUTE, pr.created_date, pr.merged_date) / 1440) as pr_time_to_merge_in_days\nfrom\n  pull_requests pr\n  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nwhere\n  pm.project_name in (${project}) and\n  pr.merged_date is not null\n  and $__timeFilter(pr.created_date)\n  and pr.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Work Done % [in $month]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct case when i.type = 'BUG' then i.id else null end) as 'Bug',\n  count(distinct case when i.type != 'BUG' and epic_key != '' then i.id else null end) as 'Strategic',\n  count(distinct case when i.type != 'BUG' and epic_key = '' then i.id else null end) as 'Non-Strategic'\nfrom\n  issues i\n  join board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\n\tjoin project_mapping pm on b.id = pm.row_id\nwhere\n  pm.project_name in (${project}) and\n  i.resolution_date is not null and\n  date(resolution_date) between\n    STR_TO_DATE('$month','%Y-%m-%d') and\n    STR_TO_DATE('$month','%Y-%m-%d') + INTERVAL 1 MONTH"
    }
   ]
  },
  {
   "title": "Average Age of Critical Outstanding Defects by Priority",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "select\n  i.priority as 'Priority',\n  AVG(TIMESTAMPDIFF(MINUTE, i.created_date, NOW()) / 1440) as 'Average Age'\nfrom\n  issues i\n  join board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\n\tjoin project_mapping pm on b.id = pm.row_id\nwhere\n  pm.project_name in (${project}) and\n  i.status = 'TODO'\n  and i.type = 'BUG'\n  and i.priority in (${priority})\ngroup by\n  i.priority"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Individual Contributor Performance",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "WITH \n_commits AS (\n  SELECT author_name, count(distinct sha) as commit_count\n  FROM commits c\n  JOIN repo_commits rc ON c.sha = rc.commit_sha\n  JOIN project_mapping pm ON rc.repo_id = pm.row_id\n  WHERE pm.project_name IN (${project}) AND $__timeFilter(authored_date)\n  GROUP BY 1\n),\n_prs AS (\n  SELECT author_name, \n         count(*) as pr_opened,\n         sum(case when status = 'MERGED' then 1 else 0 end) as pr_merged\n  FROM pull_requests pr\n  JOIN project_mapping pm ON pr.base_repo_id = pm.row_id\n  WHERE pm.project_name IN (${project}) AND $__timeFilter(created_date)\n  GROUP BY 1\n),\n_jira_issues_resolved AS (\n  SELECT \n    i.assignee_name as author_name,\n    count(distinct i.id) as issues_resolved,\n    COALESCE(sum(i.story_point), 0) as story_points_delivered\n  FROM issues i\n  JOIN board_issues bi ON i.id = bi.issue_id\n  JOIN boards b ON bi.board_id = b.id\n  JOIN project_mapping pm ON b.id = pm.row_id\n  WHERE pm.project_name IN (${project})\n    AND i.status = 'DONE'\n    AND $__timeFilter(i.resolution_date)\n  GROUP BY 1\n),\n_bugs_fixed AS (\n  SELECT \n    i.assignee_name as author_name,\n    count(distinct i.id) as bugs_fixed\n  FROM issues i\n  JOIN board_issues bi ON i.id = bi.issue_id\n  JOIN boards b ON bi.board_id = b.id\n  JOIN project_mapping pm ON b.id = pm.row_id\n  WHERE pm.project_name IN (${project})\n    AND i.status = 'DONE'\n    AND i.type = 'BUG'\n    AND $__timeFilter(i.resolution_date)\n  GROUP BY 1\n),\n_incidents_fixed AS (\n  SELECT assignee_name as author_name, count(*) as incidents_fixed\n  FROM incidents i\n  JOIN project_mapping pm ON i.scope_id = pm.row_id\n  WHERE pm.project_name IN (${project}) \n    AND $__timeFilter(resolution_date)\n  GROUP BY 1\n),\n_incidents_caused AS (\n  SELECT c.author_name, count(distinct i.id) as incidents_caused\n  FROM incidents i\n  JOIN project_incident_deployment_relationships pim ON i.id = pim.id\n  JOIN cicd_deployment_commits cdc ON pim.deployment_id = cdc.cicd_deployment_id\n  JOIN commits c ON cdc.commit_sha = c.sha\n  JOIN project_mapping pm ON i.scope_id = pm.row_id\n  WHERE pm.project_name IN (${project}) \n    AND $__timeFilter(i.created_date)\n  GROUP BY 1\n),\n_all_authors AS (\n    SELECT author_name FROM _commits \n    UNION SELECT author_name FROM _prs \n    UNION SELECT author_name FROM _jira_issues_resolved\n    UNION SELECT author_name FROM _incidents_fixed\n    UNION SELECT author_name FROM _incidents_caused\n)\n\nSELECT \n  t.author_name as 'Engineer',\n  COALESCE(c.commit_count, 0) as 'Commits',\n  COALESCE(p.pr_opened, 0) as 'PRs Opened',\n  COALESCE(p.pr_merged, 0) as 'PRs Merged',\n  COALESCE(jr.issues_resolved, 0) as 'Jira Issues Resolved',\n  COALESCE(jr.story_points_delivered, 0) as 'Story Points',\n  COALESCE(bf.bugs_fixed, 0) as 'Bugs Fixed',\n  COALESCE(f.incidents_fixed, 0) as 'Incidents Resolved',\n  COALESCE(caused.incidents_caused, 0) as 'Incidents Caused'\nFROM _all_authors t\nLEFT JOIN _commits c ON t.author_name = c.author_name\nLEFT JOIN _prs p ON t.author_name = p.author_name\nLEFT JOIN _jira_issues_resolved jr ON t.author_name = jr.author_name\nLEFT JOIN _bugs_fixed bf ON t.author_name = bf.author_name\nLEFT JOIN _incidents_fixed f ON t.author_name = f.author_name\nLEFT JOIN _incidents_caused caused ON t.author_name = caused.author_name\nWHERE t.author_name IS NOT NULL AND t.author_name != ''\nORDER BY COALESCE(c.commit_count, 0) DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Reviewer Leaderboard",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT \n  prc.author_name as 'Reviewer',\n  count(distinct pr.id) as 'PRs Reviewed',\n  count(*) as 'Comments Given'\nFROM pull_request_comments prc\nJOIN pull_requests pr ON prc.pull_request_id = pr.id\nJOIN project_mapping pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos'\nWHERE pm.project_name IN (${project})\n  AND prc.author_id != pr.author_id\n  AND $__timeFilter(prc.created_date)\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Engineer Jira Issues Resolved - Detailed View",
   "type": "table",
   "description": "Detailed list of Jira issues resolved by each engineer with issue keys and resolution reasons",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT \n  i.issue_key as 'Jira ID',\n  i.title as 'Issue Title',\n  i.type as 'Type',\n  i.priority as 'Priority',\n  i.assignee_name as 'Engineer',\n  i.original_status as 'Final Status',\n  CASE \n    WHEN i.type = 'BUG' THEN 'Bug Fix'\n    WHEN i.type = 'INCIDENT' THEN 'Incident Resolution'\n    WHEN i.type = 'TASK' THEN 'Task Completion'\n    WHEN i.type = 'REQUIREMENT' THEN 'Requirement Delivered'\n    ELSE CONCAT(i.type, ' Completed')\n  END as 'Resolution Reason',\n  DATE_FORMAT(i.resolution_date, '%Y-%m-%d %H:%i') as 'Resolution Date',\n  ROUND(i.lead_time_minutes / 1440, 1) as 'Lead Time (Days)',\n  COALESCE(i.story_point, 0) as 'Story Points',\n  i.url as 'Jira URL'\nFROM issues i\nJOIN board_issues bi ON i.id = bi.issue_id\nJOIN boards b ON bi.board_id = b.id\nJOIN project_mapping pm ON b.id = pm.row_id\nWHERE pm.project_name IN (${project})\n  AND i.status = 'DONE'\n  AND $__timeFilter(i.resolution_date)\n  AND i.assignee_name IS NOT NULL \n  AND i.assignee_name != ''\nORDER BY i.resolution_date DESC\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Issues Resolved by Type per Engineer",
   "type": "barchart",
   "description": "Summary of issues resolved by each engineer grouped by issue type and resolution reason",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT \n  i.assignee_name as 'Engineer',\n  SUM(CASE WHEN i.type = 'BUG' THEN 1 ELSE 0 END) as 'Bugs Fixed',\n  SUM(CASE WHEN i.type = 'TASK' THEN 1 ELSE 0 END) as 'Tasks Completed',\n  SUM(CASE WHEN i.type = 'REQUIREMENT' THEN 1 ELSE 0 END) as 'Requirements Delivered',\n  SUM(CASE WHEN i.type NOT IN ('BUG', 'TASK', 'REQUIREMENT') THEN 1 ELSE 0 END) as 'Other Issues'\nFROM issues i\nJOIN board_issues bi ON i.id = bi.issue_id\nJOIN boards b ON bi.board_id = b.id\nJOIN project_mapping pm ON b.id = pm.row_id\nWHERE pm.project_name IN (${project})\n  AND i.status = 'DONE'\n  AND $__timeFilter(i.resolution_date)\n  AND i.assignee_name IS NOT NULL \n  AND i.assignee_name != ''\nGROUP BY i.assignee_name\nORDER BY COUNT(*) DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Engineer Story Points & Jira IDs Summary",
   "type": "table",
   "description": "Top engineers by story points delivered from resolved Jira issues",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT \n  i.assignee_name as 'Engineer',\n  COUNT(DISTINCT i.id) as 'Issues Resolved',\n  COALESCE(SUM(i.story_point), 0) as 'Story Points',\n  ROUND(AVG(i.lead_time_minutes / 1440), 1) as 'Avg Lead Time (Days)',\n  GROUP_CONCAT(DISTINCT i.issue_key ORDER BY i.resolution_date DESC SEPARATOR ', ') as 'Recent Jira IDs'\nFROM issues i\nJOIN board_issues bi ON i.id = bi.issue_id\nJOIN boards b ON bi.board_id = b.id\nJOIN project_mapping pm ON b.id = pm.row_id\nWHERE pm.project_name IN (${project})\n  AND i.status = 'DONE'\n  AND $__timeFilter(i.resolution_date)\n  AND i.assignee_name IS NOT NULL \n  AND i.assignee_name != ''\nGROUP BY i.assignee_name\nORDER BY COALESCE(SUM(i.story_point), 0) DESC\nLIMIT 20"
    }
   ]
  }
 ]
}